version: "3.8"

services:
  hobby-log-app:
    container_name: hobby-log-app
    volumes:
      - ./static:/build/resources/main/static
      - ./jar:/jar
    build:
      context: .
      dockerfile: Dockerfile
    hostname: hobby-log-app
    ports:
      - "8082:8082"
    tty: true

networks:
  default:
    external: true
    name: grayfield
